services:
  - type: web
    name: unipast-portal
    env: node
    region: oregon
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "bash start.sh"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: DATABASE_URL
        sync: false






